### ISSUE TITLE
Improve menu title by retrieving route from Sammy

### ISSUE THREAD

**Issue by tojon** [mozilla/mozmill-dashboard#101]
Spawned from issue https://github.com/mozilla/mozmill-dashboard/issues/54 and as per @whimboo's related pull request [comment](https://github.com/mozilla/mozmill-dashboard/pull/94#discussion_r11996120), instead of relying on entries in the config file we could potentially update the dashboard title at some point by retrieving the current route from Sammy.

Or we might be able to go one step further and combine the definition for titles and callback functions used here:
https://github.com/mozilla/mozmill-dashboard/blob/master/_attachments/js/dashboard.js#L2250

**Comment by whimboo** [comment]
That would have been nice, but given that we are going to get rid of the dashboard in favor of treeherder, I'm going and close out this issue.
