### ISSUE TITLE
Simplify the Filter with a common sub-template

### ISSUE THREAD

**Issue by tojon** [mozilla/mozmill-dashboard#110]
As mentioned in this comment thread https://github.com/mozilla/mozmill-dashboard/pull/105#issuecomment-44867931, we might consider unifying the dashboard filter code with a single sub-template. Presently it is replicated across all the templates, with in most cases identical filters.

In a few reports the filters differ, so that would need to be resolved in some way.

Adding @whimboo and @andreieftimie for visibility.

**Comment by whimboo** [comment]
We are going to desupport the dashboard in favor of treeherder. So closing out as wontfix.
