### ISSUE TITLE
Make the links to test modules from report view go to the specific line

### ISSUE THREAD

**Issue by AlexLakatos** [mozilla/mozmill-dashboard#12]

**Comment by ritwikmishra** [comment]
Please tell me how to proceed in order to solve this bug?

**Comment by whimboo** [comment]
Hi @ritwikmishra and thank you for your interest in this bug! 

Here some information which will help you.

For example take the following report:
http://mozmill-release.blargon7.com/#/functional/report/569158a0e5d1513e2dbac88f33eb9226

There is a single failure. When you click on the linkified test, you will be forwarded to the current state of the test.  But it fails to add an anchor with the correct line. So currently you have to click on "show more", and find the line in the stack which includes the test name. In this case "testUninstallExtension.js:38:3". Here `38` would be the line to add as anchor:

http://hg.mozilla.org/qa/mozmill-tests/file/ab5b655cbbc5daea72c836a50ce2e490e3182302/firefox/tests/functional/testAddons/testUninstallExtension.js#l38

When you click the linkified result id at the top of the dashboard report page, you will get to the bare JSON report.

Does that make sense to you? Let me know if you need something more.

**Comment by whimboo** [comment]
We are going to desupport the dashboard in favor of treeherder. So closing out as wontfix.
