### ISSUE TITLE
Fix update channels for Balrog

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-dashboard#142]
With Balrog (aus4) we have new channels names so that the old testing channels for betas and releases do no longer exist. Similar to https://github.com/mozilla/mciconf/pull/38 we have to update the dashboard too.

**Comment by whimboo** [comment]
Btw. nightly-esr31 does no longer exist and can be removed.

**Comment by tojonmz** [comment]
Confirmed that esr-31 is removed in the PR, and ltgm.

**Comment by whimboo** [comment]
PR #143 got merged. All dashboards have been updated.
