### ISSUE TITLE
Report fallback URL when running fallback updates

### ISSUE THREAD

**Issue by ghost** [mozilla/mozmill-dashboard#37]
The dashboard currently reports the first URL during fallback but not the second URL.

For example, http://mozmill-ondemand.blargon7.com/#/update/report/23e194f1171aa4baf774928b26003cc9

It shows the partial update URL, but not the URL of the complete update that was downloaded following the fallback. Can we have both URLs reported?

**Comment by whimboo** [comment]
We are going to desupport the dashboard in favor of treeherder. So closing out as wontfix.
