### ISSUE TITLE
Display the duration as well as the start/end time

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozmill-dashboard#66]
Currently for duration we show the start and end time, which can be difficult to quickly identify how long a testrun took. We should append a calculated duration to this, either in seconds or expanded to improve readability.

Some examples:
![screen shot 2013-09-20 at 12 08 04 pm](https://f.cloud.github.com/assets/122800/1179964/2f438ce2-21e5-11e3-85ce-4623bc9342f0.png)

![screen shot 2013-09-20 at 12 07 38 pm](https://f.cloud.github.com/assets/122800/1179965/3271e558-21e5-11e3-9da5-adac51e7cd18.png)

**Comment by whimboo** [comment]
We are going to desupport the dashboard in favor of treeherder. So closing out as wontfix.
