### ISSUE TITLE
Add support to filter on Build ID

### ISSUE THREAD

**Issue by ghost** [mozilla/mozmill-dashboard#72]
Sometimes we end up with results for the same version with different build IDs. For example, today we had 25.0b11 and 25.0rc2 builds. Unfortunately both show up as Firefox 25.0 in the dashboard so there's no real way to separate the results. It would be useful to be able to generate a URL that just points to the 25.0rc2 results or just points to the 25.0b11 results. I believe this can be accomplished by adding a query parameter for the Build column.

**Comment by whimboo** [comment]
We are going to desupport the dashboard in favor of treeherder. So closing out as wontfix.
